### ISSUE TITLE
Getting Gradle build error 

### ISSUE THREAD

**Issue by aiyu-ayaan** [skydoves/landscapist#560]
Recently I came across your library and it gave me Gradle error. Can you please assist me?

`libs.version.toml`
```toml
[versions]
ktor = "3.0.0-beta-2"

[libraries]
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
```

build.gradle.kts 
```gradle
  commonMain.dependencies {
           implementation("com.github.skydoves:landscapist-coil3:2.3.8")
   }
```

Error 
```
:composeApp:commonMain: Could not resolve org.jetbrains.kotlin:kotlin-stdlib-common.
Required by:
    project :composeApp
    project :composeApp > io.ktor:ktor-serialization-kotlinx-json:3.0.0-beta-2 > io.ktor:ktor-serialization-kotlinx-json-jvm:3.0.0-beta-2 > io.ktor:ktor-serialization-kotlinx:3.0.0-beta-2 > io.ktor:ktor-serialization-kotlinx-jvm:3.0.0-beta-2 > org.jetbrains.kotlinx:kotlinx-serialization-core:1.7.2 > org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:1.7.2
    project :composeApp > io.ktor:ktor-serialization-kotlinx-json:3.0.0-beta-2 > io.ktor:ktor-serialization-kotlinx-json-jvm:3.0.0-beta-2 > org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.2 > org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.7.2
```
